'use client';

import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Download, Share2 } from 'lucide-react';

interface StyledDocumentSummaryProps {
  summary: string;
  filename: string;
  onShare?: () => void;
}

const StyledDocumentSummary: React.FC<StyledDocumentSummaryProps> = ({
  summary,
  filename,
  onShare
}) => {
  const handleDownload = () => {
    const blob = new Blob([summary], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename.split('.')[0]}-summary.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white rounded-lg border border-gray-200 shadow-sm overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-600 to-indigo-700 p-4 text-white">
        <h2 className="text-xl font-bold">Document Summary</h2>
        <p className="text-blue-100 text-sm">AI-generated analysis of {filename}</p>
      </div>

      {/* Summary content */}
      <div className="p-5">
        <div className="prose prose-blue max-w-none">
          <ReactMarkdown>{summary}</ReactMarkdown>
        </div>
      </div>
      
      {/* Divider */}
      <div className="border-t border-gray-200"></div>
      
      {/* Footer with actions */}
      <div className="px-5 py-3 bg-gray-50 flex justify-between items-center">
        <div className="text-xs text-gray-500">
          Generated by AI analysis
        </div>
        <div className="flex space-x-3">
          {onShare && (
            <button 
              onClick={onShare}
              className="flex items-center text-gray-600 hover:text-blue-600 text-sm"
            >
              <Share2 className="h-4 w-4 mr-1" />
              Share
            </button>
          )}
          <button 
            onClick={handleDownload}
            className="flex items-center text-gray-600 hover:text-blue-600 text-sm"
          >
            <Download className="h-4 w-4 mr-1" />
            Download
          </button>
        </div>
      </div>
    </div>
  );
};

export default StyledDocumentSummary;